### ISSUE TITLE
Is Coleslaw still maintained?

### ISSUE THREAD

**Issue by dertuxmalwieder** [coleslaw-org/coleslaw#193]
The most recent big change was the move to an own GitHub organization, but there have been no commits for a year and many pull requests are left unanswered. Should anyone fork Coleslaw or is the maintainer only taking a sabbatical?

Alternatively, how can we join this organization so we can actively move forward with it?

**Comment by PuercoPop** [comment]
> Is Coleslaw still maintained?

I think so, but mostly by @guicho271828 at this point.

Part of the reason for creating this organization was to make it easier to include more people. However you bring a good point in that we don't have a clear process to add new members. I know you've contributed to Coleslaw in the past and have written a Coleslaw mode for Emacs.

I think that a reasonable process for inclusion would be to submit 3 PRs and ask for it. You have already submitted 3 PRs in the past so you have that bar cleared. And you have asked to join the organization as well. 

@guicho271828 @kingcons @Ferada What are your thoughts regarding giving more people the right to merge PRs and commit? Do you think the process I've proposed above is a good one? If so let me know and I'll add @dertuxmalwieder to the organization.

**Comment by kingcons** [comment]
I strongly agree that a clear process for adding members to Coleslaw's maintainers is desirable and needed.

Coleslaw was born in 2012 when I and 2 coworkers each wrote a replacement for our wordpress installs in a single week. What started as a lark then is almost unrecognizable compared to coleslaw today. I continue to be grateful for the interest and investment in this project. In the past 5 years, I've written only 8 blog posts which is part of the reason I've taken a less active role.

I am in favor of more people having the right to merge PRs and commit, @PuercoPop. You are welcome to add @dertuxmalwieder. My main concern about coleslaw these days is not being a blocker on further development. It has long since been enough for my needs and I confess that future contributions from me are unlikely.

I will suggest two things that I think are worth consideration:

* Some discussion at least outlining future goals and, more importantly, non-goals of the project. This may help provide clarity around which PRs and issues to simply close, or how to steer potential contributors and provide feedback. It would also provide room to discuss any major shortcomings that should be addressed.
* A tagged release and blog post (maybe announce 1.0?) listing major changes made since the last "release". If the discussion about future goals finds changes are needed for which more contributors would be useful, a post would be a useful way to start that conversation.

**Comment by dertuxmalwieder** [comment]
Just to be fair: The Emacs Coleslaw mode is not mine as far as I remember. :-) But I plan to add some plug-ins and maybe some core code for more functionality which would cover my own needs, naturally. I hope that this won’t get in the way of *non-goals*.

For me, personally, Coleslaw is a blog engine, for example, not even trying to be a competitor to Hugo et al.

**Comment by dertuxmalwieder** [comment]
Thank you for the invitation. 👍 

For me, this issue is “solved”, but I’m not sure whether we should keep it for reference...?

**Comment by PuercoPop** [comment]
>  My main concern about coleslaw these days is not being a blocker on further development. It has long since been enough for my needs and I confess that future contributions from me are unlikely.

It is unlikely that I'll contribute to Colesaw in the future as well. My main concern is that there is someone left to pick up the torch. I've invited @dertuxmalwieder as a member so they can pick up the slack if they so desire.

Closing the issue, but feel free to re-open if anyone thinks there is something else that merits further discussion.
